// Fonte única dos produtos e preços da SPEC §10.1. Valores monetários em centavos.
export const products = [
  {
    id: "tijolo-6f-1",
    name: "Tijolo 6 Furos",
    category: "tijolo",
    holes: 6,
    quality: 1,
    dimensions: "9 × 13 × 23 cm",
    unitPriceCents: 90,
    thousandPriceCents: 90000,
    image: "./assets/products/tijolo-6f-primeira.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: true
  },
  {
    id: "tijolo-6f-2",
    name: "Tijolo 6 Furos",
    category: "tijolo",
    holes: 6,
    quality: 2,
    dimensions: "9 × 13 × 23 cm",
    unitPriceCents: 85,
    thousandPriceCents: 85000,
    image: "./assets/products/tijolo-6f-segunda.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: true
  },
  {
    id: "tijolo-6f-3",
    name: "Tijolo 6 Furos",
    category: "tijolo",
    holes: 6,
    quality: 3,
    dimensions: "9 × 13 × 23 cm",
    unitPriceCents: 80,
    thousandPriceCents: 80000,
    image: null,
    quoteEnabled: false,
    directContact: true,
    countsTowardDeliveryMinimum: true
  },
  {
    id: "cabeca-6f",
    name: "Cabeça 6 Furos",
    category: "complementar",
    holes: 6,
    quality: null,
    dimensions: "metade do tijolo 6F, corte no eixo vertical",
    unitPriceCents: 50,
    thousandPriceCents: null,
    image: "./assets/products/cabeca-6f.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: false
  },
  {
    id: "tijolo-8f-1",
    name: "Tijolo 8 Furos",
    category: "tijolo",
    holes: 8,
    quality: 1,
    dimensions: "9 × 19 × 19 cm",
    unitPriceCents: 100,
    thousandPriceCents: 100000,
    image: "./assets/products/tijolo-8f-primeira.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: true
  },
  {
    id: "tijolo-8f-2",
    name: "Tijolo 8 Furos",
    category: "tijolo",
    holes: 8,
    quality: 2,
    dimensions: "9 × 19 × 19 cm",
    unitPriceCents: 95,
    thousandPriceCents: 95000,
    image: "./assets/products/tijolo-8f-segunda.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: true
  },
  {
    id: "tijolo-8f-3",
    name: "Tijolo 8 Furos",
    category: "tijolo",
    holes: 8,
    quality: 3,
    dimensions: "9 × 19 × 19 cm",
    unitPriceCents: 90,
    thousandPriceCents: 90000,
    image: null,
    quoteEnabled: false,
    directContact: true,
    countsTowardDeliveryMinimum: true
  },
  {
    id: "cabeca-8f",
    name: "Cabeça 8 Furos",
    category: "complementar",
    holes: 8,
    quality: null,
    dimensions: "metade do tijolo 8F, corte no eixo vertical",
    unitPriceCents: 60,
    thousandPriceCents: null,
    image: "./assets/products/cabeca-8f.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: false
  },
  {
    id: "tijolo-macico",
    name: "Tijolo Maciço",
    category: "complementar",
    holes: null,
    quality: null,
    dimensions: null,
    unitPriceCents: 200,
    thousandPriceCents: null,
    // Imagem oficial do tijolo maciço.
    image: "./assets/products/macico.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: false
  },
  {
    id: "capote",
    name: "Capote",
    category: "complementar",
    holes: null,
    quality: null,
    dimensions: null,
    unitPriceCents: 1000,
    thousandPriceCents: null,
    image: "./assets/products/capote.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: false
  },
  {
    id: "cobogo",
    name: "Cobogó",
    category: "complementar",
    holes: null,
    quality: null,
    dimensions: null,
    unitPriceCents: 800,
    thousandPriceCents: null,
    // combogo-desenho.png mostra um conjunto de peças; cobogo.png mostra uma peça.
    image: "./assets/products/cobogo.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: false
  },
  {
    id: "tijolo-laje",
    name: "Tijolo para Laje",
    category: "complementar",
    holes: null,
    quality: null,
    dimensions: null,
    unitPriceCents: 200,
    thousandPriceCents: null,
    image: "./assets/products/tijolo-laje.png",
    quoteEnabled: true,
    directContact: false,
    countsTowardDeliveryMinimum: false
  }
];
